version:  '3'
services:
  giantbomb-api:
      build: .
      environment:
        - GIANTBOMB_API_KEY=${GIANTBOMB_API_KEY}
      volumes:
        - ./app:/app
      ports:
        - 8000:80
      container_name: giantbomb-fastapi